### ISSUE TITLE
vsr::cga2D::circle inclusion leads to multiple symbols in linking

### ISSUE THREAD

**Issue by weshoke** [wolftype/versor#12]
If you use `vsr::cga2D::circle` and similar functions defined in `vsr_cga2D_types.h` in multiple source files, you'll get a C++ linking error about mulitply defined symbols.

**Comment by wolftype** [comment]
Following the vsr_cga3d_op.h pattern, i’ve just pushed a vsr_cga2d_op.h file which encapsulates such helper functions in a vsr::cga2D::Construct class.

usage:

	#include “vsr_cga2D.h”

	using namespace vsr;
	using namespace vsr::cga2D;

	float x = 0; float y = 0; float r =1;

	auto point = Construct::point(x,y);
	auto circle = Construct::circle(x,y,r);

Taking a look at vsr_cga3D_op and making something similar for vsr_cga2D_op would be a nice contribution . . . :)
