### ISSUE TITLE
GLV makefile issue

### ISSUE THREAD

**Issue by sterlingcrispin** [wolftype/versor#13]
Hey I just downloaded and installed the newest Versor and ran into the fact that during the ./BuildAll.sh process the file:
CMakeFiles/xChain.dir/link.txt 
wast trying to find /usr/local/lib/libGLV.a , I guess assuming I had done a ./make install on it, 

I built GLV no problem so I just ran ./make install and redid buildAll and everything is fine  , just a heads up that someone else might run into the same problem

**Comment by wolftype** [comment]
Thanks -- unable to replicate this issue yet.  What os are you on? The
buildAll.sh script calls "make -C ext/glv" first, which makes glv (but does
not install it).  FindGLV.cmake is in ext/gfx/cmake/modules, and this finds
it at ext/glv/build/lib/libGLV.a my machine.  Perhaps you had an older GLV
installed already, and FindGLV.cmake found that first?  In general I'm
hoping to move away from GLV . . .

**Comment by sterlingcrispin** [comment]
I'm on OSX 10.11.2, I'll retry on another mac and see if it happens again.
I had earlier versions of GLV but none were in usr/local they were all in
other versions of allocore or the like,

On Mon, Jun 20, 2016 at 2:12 PM, Pablo Colapinto <notifications@github.com>
wrote:

> Thanks -- unable to replicate this issue yet. What os are you on? The
> buildAll.sh script calls "make -C ext/glv" first, which makes glv (but does
> not install it). FindGLV.cmake is in ext/gfx/cmake/modules, and this finds
> it at ext/glv/build/lib/libGLV.a my machine. Perhaps you had an older GLV
> installed already, and FindGLV.cmake found that first? In general I'm
> hoping to move away from GLV . . .
>
> On Sat, Jun 18, 2016 at 5:24 PM Sterling Crispin <notifications@github.com
> >
> wrote:
>
> > Hey I just downloaded and installed the newest Versor and ran into the
> > fact that during the ./BuildAll.sh process the file:
> > CMakeFiles/xChain.dir/link.txt
> > wast trying to find /usr/local/lib/libGLV.a , I guess assuming I had done
> > a ./make install on it,
> >
> > I built GLV no problem so I just ran ./make install and redid buildAll
> and
> > everything is fine , just a heads up that someone else might run into the
> > same problem
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/wolftype/versor/issues/13>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABEYX7aeWT0BMSNPgk5a6H-zgGgNHy0Fks5qNIxXgaJpZM4I5EAf
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wolftype/versor/issues/13#issuecomment-227255337>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AC1r-bw47qMm6RVB0kfF3gYXTloT6ae0ks5qNvQ7gaJpZM4I5EAf>
> .
>



-- 
http://www.sterlingcrispin.com

**Comment by wolftype** [comment]
should be resolved with updated build script
