### ISSUE TITLE
Unable to compile test code

### ISSUE THREAD

**Issue by rahulsidhu** [wolftype/versor#18]
I managed to build the examples as given but when I tried to add my own test code to use Versor as a library, I was unable to.

I followed the instructions but I get the following result:

$ ./run.sh scratch/projects/rahul/test.cpp --configure
Compiling and Running scratch/projects/rahul/test.cpp
Directory is scratch/projects/rahul
Target is test
rm: cannot remove 'bin/test': No such file or directory
make: *** No rule to make target 'test'. Stop.
./run.sh: line 22: ./bin/test: No such file or directory

Upon inspecting run.sh, it seems like the file is still incomplete.

**Comment by wolftype** [comment]
Thanks for pointing this out.  You are correct that the instructions as given are not correct. Instead, after adding your test file, please re-run build.sh (which will do the configuring and add your .cpp file to the list of targets):
```
./build.sh
./run.sh scratch/projects/rahul/test.cpp
```

**Comment by rahulsidhu** [comment]
Thanks a lot. That works!
