### ISSUE TITLE
A novice `git submodule` problem,   solved by `git submodule update --init --recursive`

### ISSUE THREAD

**Issue by goballooning** [wolftype/versor#25]
Hi Pablo, 

I just met a novice problem after running `./build.sh` , and found that `ext/gfx` directory was empty if I just `git submodule init` and `git submodule update`.

It was solved by `git submodule update --init --recursive` [1].

Cheers,
Hongying

[1]. https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules

**Comment by goballooning** [comment]
Oh I find you have pointed it out in `build.sh`:
```
if [ $DO_UPDATE = 1 ]; then
  git submodule update --init --recursive
fi
```
:)
Hongying

**Comment by wolftype** [comment]
added this to the readme!

**Comment by waldyrious** [comment]
> added this to the readme!

For future reference, that was done in commit b9f9a131ccc4efce0b1e253e4dfe044a00842364 :)
