### ISSUE TITLE
UC Regents General Public License

### ISSUE THREAD

**Issue by ahundt** [wolftype/versor#5]
Where can I see a copy of the UC Regents General Public License? I tried searching google but didn't find it. Based on your description perhaps it is one version of the [BSD License](https://en.wikipedia.org/wiki/BSD_licenses)?

**Comment by wolftype** [comment]
let me research this a bit ...

**Comment by wolftype** [comment]
update: versor is GPL

**Comment by ahundt** [comment]
@wolftype any chance either BSD or Apache v2 is possible? Otherwise I can't use it in my own open source library that is dual licensed BSD and Apache v2. Thanks for the consideration.

**Comment by wolftype** [comment]
Isn't GPL v3 compatible with Apache v2?

**Comment by ahundt** [comment]
@wolftype GPL v3 can use Apache code, but Apache code cannot use GPL v3 code https://www.apache.org/licenses/GPL-compatibility.html . In other words, you could use my library but I can't use yours.

**Comment by wolftype** [comment]
Ok let me sort this out for you so you can use the code!

**Comment by ahundt** [comment]
Awesome thanks!

**Comment by ahundt** [comment]
@wolftype hey just wanted to touch base on this, perhaps the issue could also be reopened?

**Comment by wolftype** [comment]
If we did BSD for non commercial and GPL for commercial would that work in
your case?

**Comment by ahundt** [comment]
Unfortunately I'm trying to keep my own project available to commercial projects, so the dependencies  must meet that requirement as well. Don't worry, I understand if your motivations preclude that!

**Comment by wolftype** [comment]
Ok in that case, to be most flexible, I will likely offer both BSD and GPL
licenses, and you can choose which to use for both commercial and non
commercial work. I think that offers the clearest route. I may add a strong
recommendation to keep us informed of how it is being used, for the benefit
of all. I'd rather the software be used than restrict its use!

**Comment by wolftype** [comment]
Reopened to provide a simple update:  Source code is now FreeBSD (2-clause).   Use it as you wish -- but please keep us all posted as to what you are up to!

Thanks! P

**Comment by ahundt** [comment]
That's awesome, thanks!
